### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by dmyers** [mkropat/sslfie#2]
Would it be possible to get this into Homebrew?

**Comment by mkropat** [comment]
I'd love to see sslfie in Homebrew. I wrote it from scratch on OS X. Most of the webdevs who'd find it useful are probably running OS X.

[It looks like Homebrew frowns on self-submitted formulas](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff), so I'm probably not the best person to undertake this task. I'll gladly provide assistance to anyone who wants to try.

On [the releases page](https://github.com/mkropat/sslfie/releases/latest), I've added a tarball (created with `make dist`), which is probably the starting point for any Homebrew formula. The steps to install from the tarball should be as simple as `make` then `make PREFIX=/usr install`.
